server:
  port: 8070
spring:
  application:
    name: dove-admin-config
  thymeleaf:
    cache: false
    prefix: classpath:/public/thymeleaf/

  devtools:
    restart:
      enabled: true
      exclude: public/**
  datasource:
      url: jdbc:mysql://localhost:3306/config?useUnicode=true&characterEncoding=utf8&useSSL=false
      name:
      username: root
      password: 111111
      hikari:
          data-source-properties:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show_sql: false
      properties:
          hibernate.cache.use_second_level_cache: true
          hibernate.hbm2ddl.auto: update
mybatis:
  type-aliases-package: com.licc.dove.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# mybatis 配置



