server:
  port: 8040
spring:
    datasource:
        url: jdbc:mysql://47.94.196.111:3306/config?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: 111111
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.hbm2ddl.auto: update
#      application:
#        name: spring-cloud-config-server
#      cloud:
#        config:
#          server:
#            git:
#              uri: https://github.com/licc168/spring-cloud-config    # 配置git仓库的地址
#              search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
#              username:                                             # git仓库的账号
#              password:                                             # git仓库的密码